### ISSUE TITLE
路由to和next的name为undefined

### ISSUE THREAD

**Issue by mgss** [qidaizhe11/element-pro#1]
希望作者大大能够修复~~~

**Comment by qidaizhe11** [comment]
需要更详细报错信息，我刚试了下，git clone后 npm run install, npm run dev是没问题的，node 8.10.0 + npm 6.1.0版本

**Comment by mgss** [comment]
我的环境：

* Node.js v8.11.1
* NPM v6.1.0
* Yarn v1.7.0
* Typescript v2.9.1

刚才又clone复现了下，一路发现三个问题:

* yarn install & yarn run dev 一大堆报错，所以还是按README的npm进行安装和运行成功
* npm run dev 发现以下Warning 不知道是什么Lint的配置有问题？我太菜了这个没看懂
```
$ webpack-dev-server --inline --progress --config build/webpack.dev.conf.js
 10% building modules 8/11 modules 3 active ...dules/webpack/hot/log-apply-result.jsWarning: The 'await-promise' rule requires type information.
Warning: The 'no-unused-variable' rule requires type information.
Warning: The 'no-use-before-declare' rule requires type information.
Warning: The 'return-undefined' rule requires type information.
Warning: The 'no-floating-promises' rule requires type information.
Warning: The 'no-unnecessary-qualifier' rule requires type information.
Warning: The 'no-unnecessary-type-assertion' rule requires type information.
Warning: The 'strict-type-predicates' rule requires type information.
 38% building modules 235/249 modules 14 active ...ro/src/views/Forms/StepForm/index.vue
```
* 运行成功了之后直接在/src/router/authority.ts的router.beforeEach里控制台输出to/from发现name和meta. authority都是undefined，一路查找，在/common/router.ts里authority就为匹配到相应的页面路径，不知道是path-to-regexp的问题还是什么问题，我在meta手动添加name也是一样undefined

提这个issue就是想实现不同页面跳转实现动态根据路由name显示不同的title，但是路由这部分层层封装没找见合适的修改地方。也许真的太菜了，没有看大懂，麻烦作者大大释疑.

**Comment by qidaizhe11** [comment]
根据name动态修改title确实非常重要功能，最近忙于工作进度的确拖了...

路由封装是在 src/common/router.ts 117-125行，按理router.beforeEach to/from name和meta. authority都应该有值，我今天晚上下班加紧查下问题

yarn install因为项目没附带 yarn.lock，应该是依赖版本更新，尤其最近vue-router及prettier异常导致的，有待后续依赖升级修复掉

这堆Warning我还没找到源头及解决方案，推测应该是node_modules下有些文件也经过了tslint，导致规则不匹配

**Comment by mgss** [comment]
好的，辛苦了~
还有就是run dev和build的速度可以优化吗？每次run可能要花一两分钟甚至更多，可能升级下webpack的版本有效果？
感谢作者大大~

**Comment by qidaizhe11** [comment]
webpack 3到4是不兼容更新，自己兴趣项目大可以升级，配合vue-cli 3.0 声明式配置可以节省大量配置类代码，具体到此项目，我会等vue-cli 3.0正式版推出后跟进升级

慢主要是还有一层ts-loader转译，暂时没精力考虑这部分优化
