### ISSUE TITLE
真是好东西，react太麻烦了

### ISSUE THREAD

**Issue by gudufy** [qidaizhe11/element-pro#2]
还是VUE简洁方便，希望作者能够升级到cli 3.0，谢谢。

**Comment by qidaizhe11** [comment]
暂时不具备升级条件，cli 3依赖的Typescript 2.9会导致Vue 2.5的Typescript写法严重异常（Typescript 2.7开始出现的问题），官方修复预计要Vue 2.6版了（详见https://github.com/vuejs/vue/pull/6856）。
